# Site settings
title: "phaz0n"
email: phaz0n808@gmail.com
description: "A blog"
baseurl: ""
url: "https://phaz0n.github.io"
title_description: "HackTheBox write-ups. Maybe more someday."
title_image: "/images/metroid.png"
google_analytics: UA-148827626-1
disqus_account: phaz0n
github_repository: https://github.com/phaz0n
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: _phaz0n
github_username: phaz0n
instagram_username:
reddit_username:
linkedin_link:
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link:

# Footer
footer_left: "Theme by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "phaz0n on <a href=\"https://github.com/phaz0n\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Filtering Content
show_drafts: null

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
